server:
  port: 8000

datasource:
  url: localhost:3306/tk_blog

spring:
  datasource:
    username: root
    password: Gepoint
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    hikari:
      max-lifetime: 1770000
      maximumPoolSize: 10

logging:
  level:
    cn.nxcoder.blog.dao: trace
  config: logback.xml

mybatis:
  type-aliases-package: cn.nxcoder.blog.entity
  mapper-locations:
    - classpath:mapper/*.xml

mapper:
  mappers:
    - com.epoint.core.MyMapper
  not-empty: false
  identity: MYSQL
